### ISSUE TITLE
We are waiting for the release

### ISSUE THREAD

**Issue by Paliha** [TheIndra55/TR7AE-level-viewer#1]
Hello!
I didn’t work with the typescript, I don’t know how to assemble it yet.
I don’t see any problems with trl, but as for the anniversary edition, I’m not much surprised. In drm containers, there are no scenes and models, only graphics, music, animation, and service data for parsing. In the past, I spent a lot of time, but I never found where the locations and their contents are. I'm waiting for the release, I want to see the resources of the anniversary edition in 3D.
On the screenshots of the location from the tomb rider is a legend.

**Comment by TheIndra55** [comment]
Legend and Anniversary use almost the same iteration of the engine thus they are both supported. DRM files contain more data than that since they are containers for both asset sections and data sections which contain a lot of data.

There's an online demo available at https://theindra.eu/projects/level-viewer/

**Comment by Paliha** [comment]
>>There's an online demo available

In the Big Archives, 1/4 are practically duplicates, and there are no hidden resources.
I'm surprised that the grid with the coordinates of vertices, points, etc. is still in the drm container.
  For example, comparing the container1.drm file from trl and tra, you immediately notice a significant difference in size.
The content is almost the same, except for the model mesh itself and links to it. I don't think the texture can be pulled over something else.

By the way, in the levelviewer, I really liked the multi-colored wireframe mode. Alas, in VPF this is difficult to implement.
